/**
 * @file    types.h
 * @author  Luiz Felipe (felipe.silva337@yahoo.com)
 * @brief   Header file declaring types used in Lia
 * @version 0.1
 * @date    2020-05-01
 * 
 * @copyright Copyright (c) 2020 Luiz Felipe
 */
#ifndef _LIA_TYPES_H
#define _LIA_TYPES_H

#include <inttypes.h>
#include "tree.h"

/** Token maximum size + 1 */
#define TKMAX 129

/** Number of arguments to a command */
#define CMD_ARGC 3

/** Enumeration to token's type. */
typedef enum token_type {
  TK_EOF,
  TK_ID,
  TK_SEPARATOR,
  TK_OPENBRACKET,
  TK_CLOSEBRACKET,
  TK_COLON,
  TK_COMMA,
  TK_EQUAL,
  TK_IMMEDIATE,
  TK_CHAR,
  TK_STRING
} token_type_t;

/** Structure of a token */
typedef struct token {
  struct token *next;
  struct token *last;
  int line;
  int column;

  token_type_t type;
  char text[TKMAX];
  uint8_t value;
} token_t;

/** Type of a instruction */
typedef enum inst_type {
  INST_META_NEW,
  INST_META_IMPORT
} inst_type_t;

/** Instructions' list generated by parser */
typedef struct inst {
  struct list *next;
  token_t *child;

  inst_type_t type;
} inst_t;

/** Argument to a command */
typedef struct cmd_arg {
  int name;
  int type;
} cmd_arg_t;

/** Binary tree for commands */
typedef struct cmd {
  EXTENDS_TREE(cmd);

  cmd_arg_t args[CMD_ARGC];
  char *body;
} cmd_t;

/** Operand's union */
typedef union operand {
  char reg[5];
  uint8_t imm;
  char *procedure;
} operand_t;


/** Binary tree for procedures */
typedef struct proc {
  EXTENDS_TREE(proc);

  unsigned int index;
} proc_t;

#endif /* _LIA_TYPES_H */